"""Project constants and default presets."""

from __future__ import annotations

from copy import deepcopy

STAGES = [
    "ingest",
    "prepare",
    "mutate",
    "build_legs",
    "equilibrate",
    "sample",
    "bar",
    "qc",
    "report",
]

DEFAULT_PROTOCOL_PRESETS = {
    "validation_single_point": {
        "preset": "validation_single_point",
        "force_field": "amber99sb-star-ildn-mut",
        "water_model": "tip3p",
        "lambda_windows": 4,
        "repeats": 2,
        "nvt_ps": 2,
        "npt_ps": 2,
        "production_ps": 2,
        "production_dt_ps": 0.002,
        "temperature_k": 310.0,
        "pressure_bar": 1.0,
        "overlap_threshold": 0.2,
        "max_repeat_delta_kcal_mol": 1.0,
        "max_bar_stderr_kcal_mol": 10.0,
        "window_relax_em_steps": 500,
        "window_relax_md_ps": 0.1,
        "window_relax_md_dt_ps": 0.0005,
        "same_side_double_point": False,
        "allow_charge_changing": False,
        "allow_cross_side_double_point": False,
        "gmx_bin": "gmx",
        "pmx_bin": "pmx",
        "allow_external_execute": False,
        "box_type": "dodecahedron",
        "box_padding_nm": 1.0,
        "nonbonded_cutoff_nm": 1.25,
        "vdw_switch_nm": 1.0,
        "equilibrate_retry_box_padding_nm": 2.0,
        "equilibrate_emergency_box_padding_nm": 5.0,
        "salt_concentration_m": 0.15,
        "grompp_maxwarn_genion": 2,
        "grompp_maxwarn_equilibration": 2,
        "grompp_maxwarn_sampling": 2,
        "mdrun_args": "-ntmpi 1 -ntomp 1",
    },
    "validation_priority_single_point": {
        "preset": "validation_priority_single_point",
        "force_field": "amber99sb-star-ildn-mut",
        "water_model": "tip3p",
        "lambda_windows": 8,
        "repeats": 3,
        "nvt_ps": 10,
        "npt_ps": 20,
        "production_ps": 20,
        "production_dt_ps": 0.002,
        "temperature_k": 310.0,
        "pressure_bar": 1.0,
        "overlap_threshold": 0.2,
        "max_repeat_delta_kcal_mol": 1.0,
        "max_bar_stderr_kcal_mol": 10.0,
        "window_relax_em_steps": 1000,
        "window_relax_md_ps": 0.2,
        "window_relax_md_dt_ps": 0.0005,
        "same_side_double_point": False,
        "allow_charge_changing": False,
        "allow_cross_side_double_point": False,
        "gmx_bin": "gmx",
        "pmx_bin": "pmx",
        "allow_external_execute": False,
        "box_type": "dodecahedron",
        "box_padding_nm": 1.0,
        "nonbonded_cutoff_nm": 1.25,
        "vdw_switch_nm": 1.0,
        "equilibrate_retry_box_padding_nm": 2.0,
        "equilibrate_emergency_box_padding_nm": 5.0,
        "salt_concentration_m": 0.15,
        "grompp_maxwarn_genion": 2,
        "grompp_maxwarn_equilibration": 2,
        "grompp_maxwarn_sampling": 2,
        "mdrun_args": "-ntmpi 1 -ntomp 1",
    },
    "validation_robust_single_point": {
        "preset": "validation_robust_single_point",
        "force_field": "amber99sb-star-ildn-mut",
        "water_model": "tip3p",
        "lambda_windows": 24,
        "repeats": 3,
        "nvt_ps": 50,
        "npt_ps": 200,
        "production_ps": 500,
        "production_dt_ps": 0.002,
        "temperature_k": 310.0,
        "pressure_bar": 1.0,
        "overlap_threshold": 0.2,
        "max_repeat_delta_kcal_mol": 1.0,
        "max_bar_stderr_kcal_mol": 10.0,
        "window_relax_em_steps": 2000,
        "window_relax_md_ps": 1.0,
        "window_relax_md_dt_ps": 0.0005,
        "same_side_double_point": False,
        "allow_charge_changing": False,
        "allow_cross_side_double_point": False,
        "gmx_bin": "gmx",
        "pmx_bin": "pmx",
        "allow_external_execute": False,
        "box_type": "dodecahedron",
        "box_padding_nm": 1.0,
        "nonbonded_cutoff_nm": 1.25,
        "vdw_switch_nm": 1.0,
        "equilibrate_retry_box_padding_nm": 2.0,
        "equilibrate_emergency_box_padding_nm": 5.0,
        "salt_concentration_m": 0.15,
        "grompp_maxwarn_genion": 2,
        "grompp_maxwarn_equilibration": 2,
        "grompp_maxwarn_sampling": 2,
        "mdrun_args": "-ntmpi 1 -ntomp 1",
    },
    "single_point": {
        "preset": "single_point",
        "force_field": "amber99sb-star-ildn-mut",
        "water_model": "tip3p",
        "lambda_windows": 24,
        "repeats": 2,
        "nvt_ps": 100,
        "npt_ps": 1000,
        "production_ps": 2000,
        "production_dt_ps": 0.002,
        "temperature_k": 310.0,
        "pressure_bar": 1.0,
        "overlap_threshold": 0.2,
        "max_repeat_delta_kcal_mol": 1.0,
        "max_bar_stderr_kcal_mol": 10.0,
        "window_relax_em_steps": 500,
        "window_relax_md_ps": 0.1,
        "window_relax_md_dt_ps": 0.0005,
        "same_side_double_point": False,
        "allow_charge_changing": False,
        "allow_cross_side_double_point": False,
        "gmx_bin": "gmx",
        "pmx_bin": "pmx",
        "allow_external_execute": False,
        "box_type": "dodecahedron",
        "box_padding_nm": 1.0,
        "nonbonded_cutoff_nm": 1.25,
        "vdw_switch_nm": 1.0,
        "equilibrate_retry_box_padding_nm": 2.0,
        "equilibrate_emergency_box_padding_nm": 5.0,
        "salt_concentration_m": 0.15,
        "grompp_maxwarn_genion": 2,
        "grompp_maxwarn_equilibration": 2,
        "grompp_maxwarn_sampling": 2,
        "mdrun_args": "-ntmpi 1 -ntomp 1",
    },
    "double_point": {
        "preset": "double_point",
        "force_field": "amber99sb-star-ildn-mut",
        "water_model": "tip3p",
        "lambda_windows": 32,
        "repeats": 3,
        "nvt_ps": 200,
        "npt_ps": 1500,
        "production_ps": 3000,
        "production_dt_ps": 0.002,
        "temperature_k": 310.0,
        "pressure_bar": 1.0,
        "overlap_threshold": 0.25,
        "max_repeat_delta_kcal_mol": 1.0,
        "max_bar_stderr_kcal_mol": 10.0,
        "window_relax_em_steps": 500,
        "window_relax_md_ps": 0.1,
        "window_relax_md_dt_ps": 0.0005,
        "same_side_double_point": True,
        "allow_charge_changing": False,
        "allow_cross_side_double_point": False,
        "gmx_bin": "gmx",
        "pmx_bin": "pmx",
        "allow_external_execute": False,
        "box_type": "dodecahedron",
        "box_padding_nm": 1.0,
        "nonbonded_cutoff_nm": 1.25,
        "vdw_switch_nm": 1.0,
        "equilibrate_retry_box_padding_nm": 2.0,
        "equilibrate_emergency_box_padding_nm": 5.0,
        "salt_concentration_m": 0.15,
        "grompp_maxwarn_genion": 2,
        "grompp_maxwarn_equilibration": 2,
        "grompp_maxwarn_sampling": 2,
        "mdrun_args": "-ntmpi 1 -ntomp 1",
    },
    "double_point_v2_1": {
        "preset": "double_point_v2_1",
        "force_field": "amber99sb-star-ildn-mut",
        "water_model": "tip3p",
        "lambda_windows": 40,
        "repeats": 3,
        "nvt_ps": 200,
        "npt_ps": 1500,
        "production_ps": 4000,
        "production_dt_ps": 0.002,
        "temperature_k": 310.0,
        "pressure_bar": 1.0,
        "overlap_threshold": 0.3,
        "max_repeat_delta_kcal_mol": 1.0,
        "max_bar_stderr_kcal_mol": 10.0,
        "window_relax_em_steps": 500,
        "window_relax_md_ps": 0.1,
        "window_relax_md_dt_ps": 0.0005,
        "same_side_double_point": True,
        "allow_charge_changing": True,
        "allow_cross_side_double_point": True,
        "gmx_bin": "gmx",
        "pmx_bin": "pmx",
        "allow_external_execute": False,
        "box_type": "dodecahedron",
        "box_padding_nm": 1.0,
        "nonbonded_cutoff_nm": 1.25,
        "vdw_switch_nm": 1.0,
        "equilibrate_retry_box_padding_nm": 2.0,
        "equilibrate_emergency_box_padding_nm": 5.0,
        "salt_concentration_m": 0.15,
        "grompp_maxwarn_genion": 2,
        "grompp_maxwarn_equilibration": 2,
        "grompp_maxwarn_sampling": 2,
        "mdrun_args": "-ntmpi 1 -ntomp 1",
    },
}


def preset_copy(name: str) -> dict:
    """Return an independent copy of a protocol preset."""

    if name not in DEFAULT_PROTOCOL_PRESETS:
        raise KeyError(f"Unknown protocol preset: {name}")
    return deepcopy(DEFAULT_PROTOCOL_PRESETS[name])
